import { ThemeConfig } from '@/types/workout';

export const THEMES: ThemeConfig[] = [
  {
    id: 'dark-gold',
    name: 'طلایی مشکی (لوکس)',
    primary: '#d4af37',
    secondary: '#262626',
    bg: '#1a1a1a',
    text: '#ffffff',
    tableHeaderBg: '#d4af37',
    tableHeaderColor: '#1a1a1a',
    rowEven: '#262626',
    rowOdd: '#1a1a1a',
    accent: '#d4af37'
  },
  {
    id: 'modern-blue',
    name: 'آبی مدرن',
    primary: '#1e40af',
    secondary: '#eff6ff',
    bg: '#ffffff',
    text: '#1e293b',
    tableHeaderBg: '#1e40af',
    tableHeaderColor: '#ffffff',
    rowEven: '#f1f5f9',
    rowOdd: '#ffffff',
    accent: '#3b82f6'
  },
  {
    id: 'fitness-orange',
    name: 'نارنجی انرژی',
    primary: '#ea580c',
    secondary: '#fff7ed',
    bg: '#ffffff',
    text: '#431407',
    tableHeaderBg: '#ea580c',
    tableHeaderColor: '#ffffff',
    rowEven: '#fff7ed',
    rowOdd: '#ffffff',
    accent: '#f97316'
  },
  {
    id: 'neon-green',
    name: 'سبز نئون (بدنسازی)',
    primary: '#22c55e',
    secondary: '#052e16',
    bg: '#052e16',
    text: '#f0fdf4',
    tableHeaderBg: '#22c55e',
    tableHeaderColor: '#052e16',
    rowEven: '#064e3b',
    rowOdd: '#052e16',
    accent: '#4ade80'
  },
  {
    id: 'minimal-gray',
    name: 'خاکستری مینیمال',
    primary: '#334155',
    secondary: '#f8fafc',
    bg: '#ffffff',
    text: '#0f172a',
    tableHeaderBg: '#334155',
    tableHeaderColor: '#ffffff',
    rowEven: '#f1f5f9',
    rowOdd: '#ffffff',
    accent: '#64748b'
  },
  {
    id: 'intense-red',
    name: 'قرمز آتشین',
    primary: '#991b1b',
    secondary: '#fef2f2',
    bg: '#ffffff',
    text: '#450a0a',
    tableHeaderBg: '#991b1b',
    tableHeaderColor: '#ffffff',
    rowEven: '#fef2f2',
    rowOdd: '#ffffff',
    accent: '#dc2626'
  },
  {
    id: 'royal-purple',
    name: 'بنفش سلطنتی',
    primary: '#581c87',
    secondary: '#faf5ff',
    bg: '#ffffff',
    text: '#2e1065',
    tableHeaderBg: '#581c87',
    tableHeaderColor: '#ffffff',
    rowEven: '#f5f3ff',
    rowOdd: '#ffffff',
    accent: '#a855f7'
  },
  {
    id: 'ocean-teal',
    name: 'آبی اقیانوسی',
    primary: '#0f766e',
    secondary: '#f0fdfa',
    bg: '#ffffff',
    text: '#134e4a',
    tableHeaderBg: '#0f766e',
    tableHeaderColor: '#ffffff',
    rowEven: '#f0fdfa',
    rowOdd: '#ffffff',
    accent: '#14b8a6'
  },
  {
    id: 'carbon-fiber',
    name: 'فیبر کربن',
    primary: '#525252',
    secondary: '#262626',
    bg: '#171717',
    text: '#e5e5e5',
    tableHeaderBg: '#404040',
    tableHeaderColor: '#ffffff',
    rowEven: '#262626',
    rowOdd: '#171717',
    accent: '#a3a3a3'
  },
  {
    id: 'desert-sand',
    name: 'شنی کویری',
    primary: '#78350f',
    secondary: '#fef3c7',
    bg: '#fffbeb',
    text: '#451a03',
    tableHeaderBg: '#78350f',
    tableHeaderColor: '#fcd34d',
    rowEven: '#fef3c7',
    rowOdd: '#fffbeb',
    accent: '#d97706'
  }
];
